### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by timqi**

### CODE REVIEW

**Comment by timqi** [comment]
@gitthanks can you receive?

**Comment by gitthanks** [comment]
heheh

**Comment by gitthanks** [comment]
[gitthanks.com](https://gitthanks.com)

**Comment by gitthanks** [comment]
@timqi You are not the member of [gitthanks.com](https://gitthanks.com) for now, Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
%s, you should specify using '@' to receive your bonus.

**Comment by gitthanks** [comment]
timqi, you should specify using '@' to receive your bonus.

**Comment by gitthanks** [comment]
@timqi, you should specify using '@' to receive your bonus.

**Comment by gitthanks** [comment]
@timqi, you should specify one using '@' to receive your bonus.

**Comment by timqi** [comment]
@gitthanks  ENU to @qingfeng

**Comment by gitthanks** [comment]
@timqi, you should specify the value of balance explict. Follow the instructions at [gitthanks.com](https://gitthanks.com)

**Comment by gitthanks** [comment]
@timqi, you should specify the value of bonus explict. Follow the instructions at [gitthanks.com](https://gitthanks.com)

**Comment by timqi** [comment]
@gitthanks 1.0 ENU to @qingfeng

**Comment by gitthanks** [comment]
@timqi, you should specify the value of bonus explict. Follow the instructions at [gitthanks.com](https://gitthanks.com)

**Comment by gitthanks** [comment]
@timqi, blance balance insufficient. Please deposit using [Bixin Crypto Wallet](https://bixin.im)

**Comment by gitthanks** [comment]
@timqi, ENU balance insufficient. Please login at [gitthanks.com](https://gitthanks.com) and deposit using [Bixin Crypto Wallet](https://bixin.im)

**Comment by gitthanks** [comment]
timqi, you have bonus 1.0ENU to qingfeng. @qingfeng is still not the member of [gitthanks.com](https://gitthanks.com), login using github and you can withdraw bonus to your [Bixin Crypto Wallet](https://bixin.im)

**Comment by gitthanks** [comment]
@timqi, you have bonus 1.0 ENU to qingfeng. @qingfeng is still not the member of [gitthanks.com](https://gitthanks.com), login using github and you can withdraw bonus to your [Bixin Crypto Wallet](https://bixin.im)

**Comment by gitthanks** [comment]
@timqi, you have bonus 1.0 ENU to @qingfeng. @qingfeng is still not the member of [gitthanks.com](https://gitthanks.com), login using github and withdraw bonus to your [Bixin Crypto Wallet](https://bixin.im)

**Comment by gitthanks** [comment]
@timqi, you should specify the value of bonus explict. Follow the instructions at [gitthanks.com](https://gitthanks.com)

**Comment by gitthanks** [comment]
@timqi, ENU balance insufficient. Please login at [gitthanks.com](https://gitthanks.com) and deposit using [Bixin Crypto Wallet](https://bixin.im)

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@timqi, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Pull request closed without merging**
